- hosts: server
  vars_files:
    - ./vars/main.yaml
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest
      become: true

    - name: Install EPEL Repository
      package:
        name: ['epel-release']
        state: present
      become: true

    - name: Install packages
      package:
        name: ['ufw','python3-pip']
        state: present
      become: true

    - name: Firewall
      include_tasks: ./tasks/firewall.yaml

    - name: Container
      include_tasks: ./tasks/container.yaml